package org.example.model;

// This class represents a user in the Fashion E-Retail System
// Users can be either administrators who manage products and orders, or customers who shop and place orders
public class CustomerAccount {
    // Unique identifier for the user, automatically generated by the database
    private int accountId;
    // Username used for login, must be unique across all users in the system
    private String accountName;
    // Password used for authentication, stored in plain text (in production, should be hashed)
    private String accountPassword;
    // User role that determines access level: ADMIN for administrators or CUSTOMER for regular customers
    private String accountRole; // ADMIN or CUSTOMER

    // Default constructor for creating an empty user object, typically used by database mapping frameworks
    public CustomerAccount() {
    }

    // Constructor for creating a new user without an ID, used when registering a new user
    // The database will automatically assign an ID when the user is saved
    public CustomerAccount(String accountName, String accountPassword, String accountRole) {
        this.accountName = accountName;
        this.accountPassword = accountPassword;
        this.accountRole = accountRole;
    }

    // Full constructor for creating a user with all fields including ID
    // Used when retrieving user data from the database where the ID is already known
    public CustomerAccount(int accountId, String accountName, String accountPassword, String accountRole) {
        this.accountId = accountId;
        this.accountName = accountName;
        this.accountPassword = accountPassword;
        this.accountRole = accountRole;
    }

    public int getAccountId() {
        return accountId;
    }

    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }

    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public String getAccountPassword() {
        return accountPassword;
    }

    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword;
    }

    public String getAccountRole() {
        return accountRole;
    }

    public void setAccountRole(String accountRole) {
        this.accountRole = accountRole;
    }

    // Checks if the user has administrator privileges
    // Returns true if the user's role is ADMIN, allowing access to administrative functions
    public boolean hasAdminPrivileges() {
        return "ADMIN".equals(accountRole);
    }

    // Checks if the user is a regular customer
    // Returns true if the user's role is CUSTOMER, allowing access to shopping functions
    public boolean isRegularCustomer() {
        return "CUSTOMER".equals(accountRole);
    }
}

