package org.example.model;

import java.time.LocalDateTime;

// This class represents a payment transaction associated with an order
// Tracks payment method, status, and amount for financial record keeping
public class PaymentRecord {
    // Unique identifier for the payment, automatically generated by the database
    private int paymentRecordId;
    // ID of the order that this payment is associated with, linking payment to order
    private int transactionId;
    // Method used to process the payment, chosen by the customer during checkout
    private String paymentType; // ONLINE, CARD, COD
    // Current status of the payment transaction, indicating whether it succeeded or was refunded
    private String paymentStatus; // SUCCESS, FAILED, REFUNDED
    // Amount of money processed in this payment transaction, matching the order total
    private double paymentAmount;
    // Date and time when the payment was processed or recorded in the system
    private LocalDateTime paymentTimestamp;

    public PaymentRecord() {
    }

    public PaymentRecord(int transactionId, String paymentType, String paymentStatus, double paymentAmount) {
        this.transactionId = transactionId;
        this.paymentType = paymentType;
        this.paymentStatus = paymentStatus;
        this.paymentAmount = paymentAmount;
        this.paymentTimestamp = LocalDateTime.now();
    }

    public PaymentRecord(int paymentRecordId, int transactionId, String paymentType, String paymentStatus, double paymentAmount, LocalDateTime paymentTimestamp) {
        this.paymentRecordId = paymentRecordId;
        this.transactionId = transactionId;
        this.paymentType = paymentType;
        this.paymentStatus = paymentStatus;
        this.paymentAmount = paymentAmount;
        this.paymentTimestamp = paymentTimestamp;
    }

    public int getPaymentRecordId() {
        return paymentRecordId;
    }

    public void setPaymentRecordId(int paymentRecordId) {
        this.paymentRecordId = paymentRecordId;
    }

    public int getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    public String getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    public String getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public double getPaymentAmount() {
        return paymentAmount;
    }

    public void setPaymentAmount(double paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    public LocalDateTime getPaymentTimestamp() {
        return paymentTimestamp;
    }

    public void setPaymentTimestamp(LocalDateTime paymentTimestamp) {
        this.paymentTimestamp = paymentTimestamp;
    }
}

