package org.example.model;

import java.time.LocalDateTime;

// This class represents an order placed by a customer in the Fashion E-Retail System
// Orders go through a lifecycle from creation to delivery, with admin approval required
public class PurchaseTransaction {
    // Unique identifier for the order, automatically generated by the database
    private int transactionId;
    // ID of the user who placed this order, linking the order to the customer account
    private int customerAccountId;
    // Current status of the order, which determines what actions can be performed on it
    private String transactionStatus; // CREATED, ACCEPTED, REJECTED, DELIVERED
    // Date and time when the order was originally placed by the customer
    private LocalDateTime transactionDate;
    // Total amount of money for this order, calculated from all order items and their quantities
    private double transactionTotal;

    public PurchaseTransaction() {
    }

    public PurchaseTransaction(int customerAccountId, String transactionStatus, double transactionTotal) {
        this.customerAccountId = customerAccountId;
        this.transactionStatus = transactionStatus;
        this.transactionTotal = transactionTotal;
        this.transactionDate = LocalDateTime.now();
    }

    public PurchaseTransaction(int transactionId, int customerAccountId, String transactionStatus, LocalDateTime transactionDate, double transactionTotal) {
        this.transactionId = transactionId;
        this.customerAccountId = customerAccountId;
        this.transactionStatus = transactionStatus;
        this.transactionDate = transactionDate;
        this.transactionTotal = transactionTotal;
    }

    public int getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    public int getCustomerAccountId() {
        return customerAccountId;
    }

    public void setCustomerAccountId(int customerAccountId) {
        this.customerAccountId = customerAccountId;
    }

    public String getTransactionStatus() {
        return transactionStatus;
    }

    public void setTransactionStatus(String transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    public LocalDateTime getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(LocalDateTime transactionDate) {
        this.transactionDate = transactionDate;
    }

    public double getTransactionTotal() {
        return transactionTotal;
    }

    public void setTransactionTotal(double transactionTotal) {
        this.transactionTotal = transactionTotal;
    }
}

