package org.example.model;

// This class represents a single item within an order
// Each order can contain multiple order items, one for each product that was purchased
public class TransactionLineItem {
    // Unique identifier for this order item, automatically generated by the database
    private int lineItemId;
    // ID of the order that this item belongs to, linking the item to its parent order
    private int transactionId;
    // ID of the product that was ordered, linking to the product catalog
    private int inventoryItemId;
    // Quantity of this product that was ordered by the customer
    private int itemQuantity;
    // Price of the product at the time the order was placed, stored to preserve historical pricing
    private double itemPriceAtPurchase;

    public TransactionLineItem() {
    }

    public TransactionLineItem(int transactionId, int inventoryItemId, int itemQuantity, double itemPriceAtPurchase) {
        this.transactionId = transactionId;
        this.inventoryItemId = inventoryItemId;
        this.itemQuantity = itemQuantity;
        this.itemPriceAtPurchase = itemPriceAtPurchase;
    }

    public TransactionLineItem(int lineItemId, int transactionId, int inventoryItemId, int itemQuantity, double itemPriceAtPurchase) {
        this.lineItemId = lineItemId;
        this.transactionId = transactionId;
        this.inventoryItemId = inventoryItemId;
        this.itemQuantity = itemQuantity;
        this.itemPriceAtPurchase = itemPriceAtPurchase;
    }

    public int getLineItemId() {
        return lineItemId;
    }

    public void setLineItemId(int lineItemId) {
        this.lineItemId = lineItemId;
    }

    public int getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    public int getInventoryItemId() {
        return inventoryItemId;
    }

    public void setInventoryItemId(int inventoryItemId) {
        this.inventoryItemId = inventoryItemId;
    }

    public int getItemQuantity() {
        return itemQuantity;
    }

    public void setItemQuantity(int itemQuantity) {
        this.itemQuantity = itemQuantity;
    }

    public double getItemPriceAtPurchase() {
        return itemPriceAtPurchase;
    }

    public void setItemPriceAtPurchase(double itemPriceAtPurchase) {
        this.itemPriceAtPurchase = itemPriceAtPurchase;
    }
}

