package org.example.model;

// This class represents a product in the Fashion E-Retail System inventory
// Products are managed by administrators and can be purchased by customers
public class InventoryItem {
    // Unique identifier for the product, automatically generated by the database
    private int itemId;
    // Name of the product that will be displayed to customers when browsing
    private String itemName;
    // Detailed description of the product providing information about its features and characteristics
    private String itemDescription;
    // Price of the product in dollars, used to calculate order totals and cart subtotals
    private double itemPrice;
    // Current quantity of this product available in inventory for purchase
    private int itemStock;

    public InventoryItem() {
    }

    public InventoryItem(String itemName, String itemDescription, double itemPrice, int itemStock) {
        this.itemName = itemName;
        this.itemDescription = itemDescription;
        this.itemPrice = itemPrice;
        this.itemStock = itemStock;
    }

    public InventoryItem(int itemId, String itemName, String itemDescription, double itemPrice, int itemStock) {
        this.itemId = itemId;
        this.itemName = itemName;
        this.itemDescription = itemDescription;
        this.itemPrice = itemPrice;
        this.itemStock = itemStock;
    }

    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemDescription() {
        return itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public double getItemPrice() {
        return itemPrice;
    }

    public void setItemPrice(double itemPrice) {
        this.itemPrice = itemPrice;
    }

    public int getItemStock() {
        return itemStock;
    }

    public void setItemStock(int itemStock) {
        this.itemStock = itemStock;
    }
}

